# render.yaml (create this file in your project root)
services:
  - type: web
    name: voicetranscript
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --worker-class sync --max-requests 100 --preload
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: HF_HOME
        value: /tmp/huggingface_cache
      - key: TRANSFORMERS_CACHE
        value: /tmp/huggingface_cache
      - key: HF_DATASETS_CACHE
        value: /tmp/huggingface_cache

---

# Alternative gunicorn command for your current setup:
# Update your Render service start command to:
gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --worker-class sync --max-requests 100 --preload